import Head from "next/head";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { goerli } from "wagmi/chains";
import Body from "@/components/body";
import { publicProvider } from "wagmi/providers/public";
import { alchemyProvider } from "wagmi/providers/alchemy";

export default function Home() {
  const api = process.env.ALCHEMY_KEY!;
  const { chains, provider, webSocketProvider } = configureChains(
    [goerli],
    [publicProvider()]
  );
  const client = createClient({
    autoConnect: true,
    provider,
    webSocketProvider,
  });
  return (
    <WagmiConfig client={client}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body />
    </WagmiConfig>
  );
}
